language: node_js
node_js:
- 6.12.0
- 6.12.1
- 8.9
- 8.9.1
deploy:
  provider: npm
  email: doug@onvelocity.com
  api_key:
    secure: FN3wittmD0EcedqLpSIvDrFhowFalY+M5x9ylzrcAR52D94pRxEhBWmDMhhAfnBDjPzMXD5gOV+yvMF2YGNuVO4WVKOMRyKbN2jx5ZXbkkIgkKVqj69ioQcClBEdU6HHPlwqxwxKqGc9Jssbo6yZDUVbC4DnZLsg/t7ZJqeU0+5NHttx1j83cphziklcEnxY4Z4Mgq6xJ/6HGLNnvIx4tDnwbJ+JNZuAj4R1af7LV6B/9AOiZcItZBgJ1BiJ+QCxEmuzkFG8lkx8cCIhy5HAYY/bwsx3632rOfJX/Rt9iDdwSq8Xz1mOqG0BRywkZ+PUobUcJNLI+nEAyXSEVdY4k+UJOIj0IqnU5bgasNF9KlSaPXbVwN8oq2kqDAhvDGZqvpMPAFS/cAfuZOyjvabLZRUUqKZzQQAyYQ8MLKnzDoen5bLPhN65p6DLCWJqKWmW3P6yhDI30m7ee3LGf1zvGklnAm7LC0E3qUwpWqRgASHoz2mTm+hlfHd6uxsr6VDguKFHJ2ZifNPMCyrS4DiGfpPcOyHwfqvJHCknWiWVTn0giyPDSVuQLSeW+/CxRmrt4PyEa7VfdSFGc9Uz/ZfwNRmAr30tdH/djyXvlrMDFqee6qvHfHdQyubQKlQWQ6Lv3Npfmlx2u0ZT3LsT7MzYVF7/sYVIU0b+KCB+4ATMS7Y=
  on:
    tags: true
    repo: javadoug/swizzle-params
script:
  npm run test-report
