language: node_js
node_js:
- node
deploy:
  provider: npm
  email: "doug@onvelocity.com"
  api_key: FbQDN1Wu9eFVCwtgWAafDGt7hfA2Z/Iosow0q3jT/v9s6V64cUaBbLwCGZnVjGUmWAT4dW2r5AJtNA8nyhAc84O+0oOyikVb2LFSH4R60Js4UzgXCsdR6zY194EIezSQxruEPCE0UXL0c+hXIDLeeKArWKDMe2duI4jS4Ql96QYfbLwPgD6ghFE0wU4gnvciruCjkysSYZ6zEja+A0ElLyOraPxoHbwtmSGp5D+F4suQBD1CzhYjdoKzaiUEmcFzFvuAb1Rg1g+w8eLS6WkkgtKRkcQbygqkx9XdkTd1kLvb8cnCSjgD2LzN358QJgVfHRJoQ8YveQPdZEhiud7xshLFda7NAF2En1BIMH5c3jQ51mDSyUuKsdsyU6HW+2015hY72OlUx8znAC4QgyHcXLefvUQxti5DHX8pwyMNED0ISF890zSotsa9RezX2+f/bRPsx3ANHyZgWhzNni7zZP9y5ecySwRfVs/7uVAFlhgphNHXrrLIkqAbDQfk3WbFuB9fabfrvNG7nmJJvRHASFJ3wgkMuGVzX8l+0An6kciR1iW23epyRiO+7AWPXF5z45UiTX//udLIhnk7ijwqbvRtzVUKMmlzEUyP1IfDwj9YuNabrUKV8gRVt//kdee5xMOwbgGYICnHZVkDrHgmvj0LtDlFSN7vBaonF9JKOKE=
  on:
    tags: true
  tag: next